### ISSUE TITLE
Script failing with error "The event definition only contains modifications"

### ISSUE THREAD

**Issue by jsilve24** [asoroa/ical2org.py#55]
Hello, first off thank you for all your hard work creating and maintaining this package. 

I am getting the following odd error 

```
--2024-09-09 09:11:13--  https://outlook.office365.com/owa/calendar/rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr/calendar.ics
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving outlook.office365.com (outlook.office365.com)... 52.96.109.210, 52.96.33.82, 52.96.109.162, ...
Connecting to outlook.office365.com (outlook.office365.com)|52.96.109.210|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 375973 (367K) [text/calendar]
Saving to: ‘/home/jds6696/.cache/ical2org/psu_cal.ics’


               /home/jds6696/   0%[                                               ]       0  --.-KB/s               
              /home/jds6696/.  30%[=============>                                 ] 112.00K   556KB/s               
             /home/jds6696/.c  82%[=====================================>         ] 304.00K   749KB/s               
/home/jds6696/.cache/ical2org 100%[==============================================>] 367.16K   817KB/s    in 0.4s    

2024-09-09 09:11:17 (817 KB/s) - ‘/home/jds6696/.cache/ical2org/psu_cal.ics’ saved [375973/375973]

Traceback (most recent call last):
  File "/home/jds6696/.local/bin/ical2orgpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ical2orgpy/__init__.py", line 236, in main
    convertor(ics_file, org_file)
  File "/usr/lib/python3.12/site-packages/ical2orgpy/__init__.py", line 74, in __call__
    for comp in recurring_ical_events.of(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/recurring_ical_events.py", line 1124, in of
    return CalendarQuery(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/recurring_ical_events.py", line 972, in __init__
    component_adapter.collect_components(calendar, self._skip_errors)
  File "/usr/lib/python3.12/site-packages/recurring_ical_events.py", line 640, in collect_components
    result.append(Series(components))
                  ^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.12/site-packages/recurring_ical_events.py", line 335, in __init__
    raise InvalidCalendar(
recurring_ical_events.InvalidCalendar: The event definition for 040000008200E00074C5B7101A82E008000000004057F23F34B7DA01000000000000000010000000D1AE0F3D9C1EF743A355CF1299169358 only contains modifications.
```

Looking at the produced ical file it seems to relate to this event:

```
BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E008000000004057F23F34B7DA01000000000000000
 010000000D1AE0F3D9C1EF743A355CF1299169358
RECURRENCE-ID;TZID=Eastern Standard Time:20240625T120000
SUMMARY:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DTSTART;TZID=Eastern Standard Time:20240625T120000
DTEND;TZID=Eastern Standard Time:20240625T130000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20240909T131145Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:3
LOCATION:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
X-MICROSOFT-CDO-APPT-SEQUENCE:3
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-ISRESPONSEREQUESTED:FALSE
END:VEVENT
```

I can go into my calendar and delete this event but I have to do this to a bunch of events and its a huge pain. Weirdly, most of these events are in the past and I had used this script successfully for months -- with those events there -- without error. I checked my package manager logs and there has been no recent updates to idcal2org.py that I can see causing this... so a bit confused. Either way I am getting this error for a bunch of events -- if I delete them all the problem goes away. But its enough of a pain I figured I would write this up. 

My sincere appologies if I have not provided the relevant details as I am having trouble parsing the ical file myself. 

Any help would be most appreciated. 

Justin 

For reference, here is another example of an event that caused probems before I deleted it from google calendar. 

```
BEGIN:VEVENT
DESCRIPTION:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxx
UID:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
RECURRENCE-ID;TZID=Eastern Standard Time:20240501T120000
SUMMARY:xxxxxxxxxxxxxxxxxxxxxxxxxx
DTSTART;TZID=Eastern Standard Time:20240501T120000
DTEND;TZID=Eastern Standard Time:20240501T133000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20240909T130506Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:4
LOCATION:XXX
X-MICROSOFT-CDO-APPT-SEQUENCE:4
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-ISRESPONSEREQUESTED:FALSE
END:VEVENT
```

**Comment by jsilve24** [comment]
really not sure what was going on there. I updated some seemingly unrelated packages recently and the error went away... closing for now.
